### PR TITLE
Updates for Compatibility with Latest OpenAI API

### PR DESCRIPTION
**Pull request by aleksa-codes**
Hi @alvesvaren,

First, thank you for creating this library. It helped me a lot when I switched from the Chat Completion API to the Assistants API using `zod` for tool validation. I couldn't have done it without your library.

I had to make a few changes to `src/index.ts` to work with the latest API version. The `retrieval` tool was replaced with `file_search`, and there were some type changes. I am currently using this modified file in my final thesis project. I thought it would be a good idea to contribute these changes back to your project. If accepted, I can use this library as an npm package.

Here are the changes:
1. Updated the OpenAI GPT model in the examples to `gpt-4o-mini`.
2. Updated the handling of `messages.data[0].content[0]` in the `examples/openai-assistants.ts` example to account for a new third type.
3. Changes to `src/index.ts`:
   - Updated type `OpenAI.Beta.AssistantCreateParams.AssistantToolsFunction` to `OpenAI.Beta.FunctionTool` [openai-node link](https://github.com/openai/openai-node/blob/22896e88e97c0e8621bf74c666a6fc7d9d832267/src/resources/beta/assistants.ts#L662)
   - Updated type `OpenAI.Beta.Assistant.Retrieval` to `OpenAI.Beta.FileSearchTool` [openai-node link](https://github.com/openai/openai-node/blob/22896e88e97c0e8621bf74c666a6fc7d9d832267/src/resources/beta/assistants.ts#L631)
   - Updated type `OpenAI.Beta.Assistant.CodeInterpreter` to `OpenAI.Beta.CodeInterpreterTool` [openai-node link](https://github.com/openai/openai-node/blob/22896e88e97c0e8621bf74c666a6fc7d9d832267/src/resources/beta/assistants.ts#L624)
   - Fixed and updated the aliases for the variable/const `t` and changed `retrieval: { type: "retrieval" }` to `fileSearch: { type: "file_search" }`.
   - Updated `src/index.test.ts`: `type: "retrieval"` to `type: "file_search"`.
4. Updated readme

Thanks again for your work on this library.

### CODE REVIEW

**Comment by aleksa-codes** [comment]
I worked with Yarn locally and didn't realize that the `openai` dependency needs an upgrade, as does the `zod` peer dependency.

**Comment by alvesvaren** [comment]
Nice! Thank you, I will have a look at it later.

I can update the dependencies and add a  changeset file :) 

dependabot is just for automating new updates, you can update them manually too if you want

**Comment by alvesvaren** [comment]
Wasn't able to update your branch for some reason, so moved this to #189

**Comment by alvesvaren** [comment]
Now released as part of v0.12.0 :D, thanks again @aleksa-codes

**Comment by aleksa-codes** [comment]
@alvesvaren Nice! 😄 Thank you again for this package.

**Pull request closed without merging**
